apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: anddd7@icloud.com
    # for staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        webhook:
          groupName: acme.mesh-shaped.top
          solverName: alidns
          config:
            regionId: cn-hangzhou
            accessKeyIdRef:
              name: alidns-secret
              key: access-key-id
            accessKeySecretRef:
              name: alidns-secret
              key: access-key-secret

