#!/bin/bash

BLOG_DIR="docs/post"
SIDEBAR_FILE="docs/_sidebar.md"

function create_blog() {
  title=""
  while getopts "t:" opt; do
    case $opt in
    t)
      title="$OPTARG"
      ;;
    \?)
      echo "Usage: $0 create [-t <title>]"
      exit 1
      ;;
    esac
  done

  current_date=$(date +"%Y%m%d-%H%M%S")
  file_name="$current_date.md"
  file_path="$BLOG_DIR/$(date +"%Y")/$file_name"

  echo "# $title" >>"$file_path"

  echo "Blog post created: $file_path"
}

function publish_blog() {
  while getopts "f:" opt; do
    case $opt in
    f)
      file_path="$OPTARG"
      ;;
    \?)
      echo "Usage: $0 publish [-f <file_path>]"
      exit 1
      ;;
    esac
  done

  if [ -z "$file_path" ]; then
    echo "Please provide the file path using -f option."
    exit 1
  fi

  year=$(echo "$file_path" | awk -F'/' '{print $3}')
  title=$(head -n 1 "$file_path" | sed -n 's/^# \(.*\)$/\1/p')
  file_path=$(echo "$file_path" | sed 's/^docs\///')

  sed -i "/\* $year/ a\*\* [$title]($file_path \"$title\")" "$SIDEBAR_FILE"
  echo "Blog post published to sidebar: $file_path"
}

case "$1" in
create)
  shift
  create_blog "$@"
  ;;
publish)
  shift
  publish_blog "$@"
  ;;
*)
  echo "Usage: $0 {create|publish} [options]"
  exit 1
  ;;
esac
