apiVersion: v1
kind: Secret
metadata:
  name: alibabacloud-cloud-config
  namespace: external-dns
type: Opaque
stringData:
  alibabacloud-cloud-config.yaml: |
    accessKeyId: "${ALICLOUD_DNS_MANAGER_AK}"
    accessKeySecret: "${ALICLOUD_DNS_MANAGER_SK}"
    region: "cn-hangzhou"
    vpcId: "xxx"
