apiVersion: apps/v1
kind: Deployment
metadata:
  name: docsify
  labels:
    app: docsify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docsify
  template:
    metadata:
      labels:
        app: docsify
    spec:
      containers:
      - name: docsify
        image: ${DOCSIFY_IMAGE_TAG}
        ports:
        - containerPort: 3000
