apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docsify
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Blog"
    gethomepage.dev/description: "Blog powered by docsify"
    gethomepage.dev/group: "Website"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: anddd7.mesh-shaped.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docsify
            port:
              number: 80
  tls:
  - hosts:
    - "*.mesh-shaped.top"
    secretName: mesh-shaped-top-wild-tls
