#!/bin/bash

# instructions
# ------------
# nothing special but need to replace the image mirror

helm upgrade --install ingress-nginx ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace \
    -f helm/values.yaml
