config:
  # settings
  settings:
    title: Anddd7

    layout:
      Deployment:
        style: row
        columns: 4

  # bookmarks
  bookmarks:
  - Cloud-Native:
    - CNCF:
      - href: https://landscape.cncf.io/

  - AI:
    - ChatGPT:
      - href: https://chat.openai.com/
    - txyz | paper reader:
      - href: https://app.txyz.ai/

  - UI:
    - emojiCopy:
      - href: https://emojicopy.com/

  - Format:
    - JSON Hero:
      - href: https://jsonhero.io/
    - regex101:
      - href: https://regex101.com/
    - Regex Vis:
      - href: https://regex-vis.com/
    - Subnet Calculator:
      - href: https://www.davidc.net/sites/default/subnets/subnets.html
    - CIDR Visualizer:
      - href: https://cidr-subnet.netlify.app/

  # services
  services:
  - Deployment:
    - Excalidraw:
        href: https://excalidraw-anddd7.vercel.app/
        description: Forked excalidraw, support free ZH fonts
        icon: https://docs.excalidraw.com/img/favicon.png

  - Coding:
    - Github:
        href: https://github.com/Anddd7
        description: My Github Profile
        icon: https://github.githubassets.com/favicons/favicon.png
    - Anddd7/grpcbin:
        href: https://github.com/Anddd7/grpcbin
        description: A gRPC testing tool
        icon: https://github.githubassets.com/favicons/favicon.png
    - Anddd7/rubber-duck:
        href: https://github.com/Anddd7/rubber-duck
        description: A testing toolset for kubernetes
        icon: https://github.githubassets.com/favicons/favicon.png


  # widgets
  widgets:
  - kubernetes:
      cluster:
        show: true
        cpu: true
        memory: true
        showLabel: true
        label: "cluster"
      nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true
  - search:
      provider: [duckduckgo, google]
      target: _blank

  # kubernetes
  kubernetes:
    mode: cluster


serviceAccount:
  create: true
  name: homepage

enableRbac: true

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "this!"
      gethomepage.dev/group: "Deployment"
      gethomepage.dev/icon: "homepage.png"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: homepage.mesh-shaped.top
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - "*.mesh-shaped.top"
      secretName: mesh-shaped-top-wild-tls
