config:
  bookmarks:
  - Developer:
    - Github:
      - abbr: GH
        href: https://github.com/Anddd7
  services:
  - My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

  - My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

  - My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
  widgets:
  # show the kubernetes widget, with the cluster summary and individual nodes
  - kubernetes:
      cluster:
        show: true
        cpu: true
        memory: true
        showLabel: true
        label: "cluster"
      nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true
  - search:
      provider: duckduckgo
      target: _blank
  kubernetes:
    mode: cluster
  settings:

serviceAccount:
  create: true
  name: homepage

enableRbac: true

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "Dynamically Detected Homepage"
      gethomepage.dev/group: "Dynamic"
      gethomepage.dev/icon: "homepage.png"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: homepage.mesh-shaped.top
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - "*.mesh-shaped.top"
      secretName: mesh-shaped-top-wild-tls
