#!/bin/bash

# install the alibaba cloud config secret
kubectl kustomize kustomization | envsubst | kubectl apply -f -

helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/

helm upgrade --install \
    external-dns external-dns/external-dns \
    --namespace external-dns \
    --create-namespace \
    --version 1.14.4 \
    -f helm/values.yaml
