#!/bin/bash

# instructions
# ------------
# alibaba provider can read credentials from a file
# so we need to create a secret and mount into the pod

# prepare the secret
kubectl kustomize kustomization | envsubst | kubectl apply -f -

# install cert-manager
helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/

helm upgrade --install \
    external-dns external-dns/external-dns \
    --namespace external-dns \
    --create-namespace \
    --version 1.14.4 \
    -f helm/values.yaml
