#!/bin/bash

# instructions
# ------------
# cert-manager doesn't support alidns as a dns01 provider out of the box.
# so you need to use a webhook to make it work, there are 3 alidns-webhook
# - (out-of-date) https://github.com/pragkent/alidns-webhook
# - (no image mirror) https://github.com/DEVmachine-fr/cert-manager-alidns-webhook
# - [checked] https://github.com/wjiec/alidns-webhook

# cert-manager
helm repo add jetstack https://charts.jetstack.io

helm upgrade --install \
    cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --version v1.14.5 \
    --set installCRDs=true \
    -f helm/values.yaml

# prepare the secret for aksk and cluster issues
kubectl kustomize kustomization | envsubst | kubectl apply -f -

# alidns webhook
helm upgrade --install alidns-webhook alidns-webhook \
    --repo https://wjiec.github.io/alidns-webhook \
    --namespace cert-manager \
    --create-namespace \
    --set groupName=acme.mesh-shaped.top
