#!/bin/bash

helm repo add jetstack https://charts.jetstack.io --force-update
helm repo add cert-manager-alidns-webhook https://devmachine-fr.github.io/cert-manager-alidns-webhook

helm repo update

# cert-manager
helm upgrade --install \
    cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --version v1.14.5 \
    --set installCRDs=true \
    -f helm/values.yaml

helm upgrade --install \
    cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --version v1.14.5 \
    -f helm/values.yaml

# alidns webhook
helm upgrade --install \
    alidns-webhook cert-manager-alidns-webhook/alidns-webhook
