name: beian

on:
  push:
    paths:
      - 'beian/index.html'
      - 'beian/kustomization/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Kubernetes
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            cp beian/index.html beian/kustomization/index.html
            kubectl kustomize beian/kustomization | envsubst | kubectl apply -f -